#include <stdlib.h>
#include <stdio.h>
#include <string.h>

typedef void (* command_function_ptr) ();

#define MAX_PARAMS 10
#define TEMPORARY_ARRAY_SIZE 32
#define AVAILABLE_COMMANDS 2

char* params[MAX_PARAMS] = { 0 }; // MAX: 10 params
char tmp_array[TEMPORARY_ARRAY_SIZE] = { 0 }; // temporary variable
int new_line_found = 0;

command_function_ptr command_ptr[AVAILABLE_COMMANDS] = { 0 };
char* command_name[AVAILABLE_COMMANDS] = { 0 };

#ifdef ARDUINO
	// ~~~~~~~~~~ ARDUINO
	int readChar() {
		return Serial.read();
	}
	
	void setup_command_arrays() {
		// AUTOGENERATED
	}
	
	void sendInvalidCmdResponse() {
	}
	
#endif

#ifndef ARDUINO
	// ~~~~~~~~~~ PLAIN C
	int readChar() {
		char* text = "_ping\n_analogRead 5\n_some_invalid_command\n";
		static int next_return = 0;
		int ret = (int) text[next_return];
		next_return = next_return + 1;
		if(next_return >= strlen(text))
			next_return = 0;
		return ret;
	}
	
	void delay(int d) { }
	
	void _ping() {
		printf("ping()\n");
	}
	
	void _analogRead() {
		printf("_analogRead() PIN %s\n", params[1]);
	}
	
	void setup_command_arrays() {
		command_ptr[0] = _ping;
		command_name[0] = "_ping";
		command_ptr[1] = _analogRead;
		command_name[1] = "_analogRead";
	}
	
	void sendInvalidCmdResponse() {
		printf("INVALID FUNCTION: '%s'\n", params[0]);
	}
	
#endif

void read_one_param() {
	
	int i;
	for(i=0; i<TEMPORARY_ARRAY_SIZE; i++)
		tmp_array[i] = 0x00; // reset
	
	int incomingByte;
	int pos = 0;
	while (pos < (TEMPORARY_ARRAY_SIZE-1)) {

		incomingByte = readChar();
		if(incomingByte == -1) {
			// no data
			if(pos == 0 && params[0] == NULL) {
				// wait 10ms only if no data was received
				delay(10);
			}
			continue;
		}

		// " " == 32
		if(incomingByte == 32) {
			if(pos == 0) {
				// Ignore leading white spaces
				continue;
			}
			// got a space... return!
			return;
		}
		
		// "\\n" == 10
		if(incomingByte == 10) {
			new_line_found = 1;
			return;
		}

		tmp_array[pos++] = incomingByte;

	} // while
	
	// pos == (TEMPORARY_ARRAY_SIZE-1)
	return;
	
}

void read_parameters() {

	int i;
	for(i=0; i<MAX_PARAMS; i++) {
		if(params[i] != NULL) {
			free(params[i]); // free
			params[i] = NULL; // reset
		}
	}
	
	int param_index = 0;
	new_line_found = 0;
	
	for(param_index=0; param_index<MAX_PARAMS && !new_line_found; param_index++) {
		read_one_param();
		
		if(strlen(tmp_array) == 0 &&  new_line_found) {
			return;
		}
		
		params[param_index] = (char*) malloc(strlen(tmp_array)+1);
		strcpy(params[param_index], &tmp_array[0]);
	}
	
	if(new_line_found) {
		return;
	} else {
		while(! new_line_found) {
			read_one_param();
		}
	}
	
}

void setup() {
	setup_command_arrays();
}

command_function_ptr get_function_by_name(char* name) {
	int i;
	for(i=0; i<AVAILABLE_COMMANDS; i++) {
		if(strcmp(name, command_name[i]) == 0) {
			return command_ptr[i];
		}
	}
	return NULL;
}

void loop() {
	read_parameters();
	
	#ifndef ARDUINO
	int i;
	for(i=0; i<MAX_PARAMS; i++) {
		if(params[i] != NULL) {
			printf("Parametro[%d]: %s\n", i, params[i]);
		}
	}
	#endif
	
	command_function_ptr command = get_function_by_name(params[0]);
	if(command != NULL) {
		(command)();
	} else {
		// INVALID FUNCTION NAME
		sendInvalidCmdResponse();
	}
}

#ifndef ARDUINO

int main() {
	setup();
	loop();
	loop();
	loop();
	return 0;
}

#endif
