#!/bin/bash

# Configuraciones
USER="horacio"
PID="/tmp/py-arduino-cfacha.pid"
LOG="/tmp/py-arduino.log"

test -e /etc/py-arduino.conf && source /etc/py-arduino.conf

if [ "$(id -u)" -ne "0" ] ; then
	echo "ERROR: you must run this as root"
	exit 1
fi

BASEDIR=$(cd $(dirname $0)/..; pwd)

case "$1" in
"start")
	set -u
	echo -n "Starting py-arduino... "
	$BASEDIR/cfacha/run.sh --pidfile2=$PID --daemonize2=$LOG --uid=$USER
	echo "OK"
	;;
"stop")
	set -u
	echo -n "Stoping py-arduino... "
	$BASEDIR/cfacha/run.sh --uid=$USER --stop $PID
	echo "OK"
	[ -e $PID ] && rm -f $PID
	;;
*)
	echo "ERROR: valid options: [start|stop]"
	exit 1
	;;
esac

